### ISSUE TITLE
Batched Resolvers are bugged because of mismatching source types

### ISSUE THREAD

**Issue by Gilligan128** [graphql-java/graphql-java-tools#123]
Given:
schema = "type Query {
   items: [Item]
}
type Item {
    batchedId: String!
}"

@Component
class Query : GraphQLQueryResolver {

    fun items() : List<Item> {
        return listOf(Item(), Item())
    }
}

@Component
class ItemResolver : GraphQLResolver<Item> {
    @Batched
    fun batchedId(items : List<Item>) = items.mapIndexed{ index, _ -> "juice " + index}
}

When I run this in GraphiQL:
query {
  items{
    batchedId
  }
}

Then I see this error in the app: 
Source type (com.ford.orcs.doorman.endpoints.describe.Item) is not expected type (java.lang.Iterable)!
        at com.coxautodev.graphql.tools.MethodFieldResolver$createDataFetcher$1.invoke(MethodFieldResolver.kt:51) ~[graphql-java-tools-4.3.0.jar:na]
        at com.coxautodev.graphql.tools.MethodFieldResolver$createDataFetcher$1.invoke(MethodFieldResolver.kt:19) ~[graphql-java-tools-4.3.0.jar:na]
        at com.coxautodev.graphql.tools.MethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:131) ~[graphql-java-tools-4.3.0.jar:na]
        at com.coxautodev.graphql.tools.BatchedMethodFieldResolverDataFetcher.get(MethodFieldResolver.kt:138) ~[graphql-java-tools-4.3.0.jar:na]

From what I can tell, the MethodFieldResolver looks for an Iterable as the source argument only when a resolver is batch, but is seeing Item, which is the correct Source argument according to the DataFetchingEnvironment.

**Comment by Gilligan128** [comment]
If I get time (I have a new baby) I will make a PR for this.

**Comment by Gilligan128** [comment]
I may have spoken too soon. I noticed that the EndtoEndSpec.groovy uses a BatchedExecutionStrategy, whereas the default is AsyncExecutionStrategy. I will set the strategy in my code and if it starts working, close this issue

**Comment by Gilligan128** [comment]
I see that this probably would have been obvious if I were more familiar with GraphQL-Java
