### ISSUE TITLE
java.lang.IncompatibleClassChangeError: org/objectweb/asm/MethodVisitor.visitCode()V

### ISSUE THREAD

**Issue by nosaku** [graphql-java/graphql-java-tools#127]
Getting the following error. Any idea on resolving this? I am using JDK 1.8 to compile.

		
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-java</artifactId>
			<version>6.0</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-java-tools</artifactId>
			<version>4.3.0</version>
		</dependency>
		<dependency>
			<groupId>com.graphql-java</groupId>
			<artifactId>graphql-java-servlet</artifactId>
			<version>4.6.1</version>
		</dependency>

Caused by: java.lang.IncompatibleClassChangeError: org/objectweb/asm/MethodVisitor.visitCode()V
	at com.esotericsoftware.reflectasm.MethodAccess.get(MethodAccess.java:126)
	at com.coxautodev.graphql.tools.ResolverDataFetcher.<init>(ResolverDataFetcher.kt:86)
	at com.coxautodev.graphql.tools.ResolverDataFetcher$Companion.create(ResolverDataFetcher.kt:81)
	at com.coxautodev.graphql.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:110)
	at com.coxautodev.graphql.tools.SchemaParser$createObject$$inlined$forEach$lambda$1.apply(SchemaParser.kt:47)
	at graphql.schema.GraphQLObjectType$Builder.field(GraphQLObjectType.java:153)
	at com.coxautodev.graphql.tools.SchemaParser.createObject(SchemaParser.kt:108)
	at com.coxautodev.graphql.tools.SchemaParser.parseSchemaObjects(SchemaParser.kt:69)
	at com.coxautodev.graphql.tools.SchemaParser.makeExecutableSchema(SchemaParser.kt:93)
	at com.sample.graphql.GraphQLEndpoint.buildSchema(GraphQLEndpoint.java:25)
	at com.sample.graphql.GraphQLEndpoint.<init>(GraphQLEndpoint.java:16)

**Comment by nosaku** [comment]
Got it... I was having other JARs related to Hibernate, JUnit etc. and may be they are quite old. Removed all of them it worked fine. I will add the other dependencies in order and the latest versions so I may not get this error again.
