### ISSUE TITLE
NoClassDefFoundError with graphql-java 8.0

### ISSUE THREAD

**Issue by slisaasquatch** [graphql-java/graphql-java-tools#128]
This is the error

```
Caused by: java.lang.NoClassDefFoundError: graphql/language/TypeExtensionDefinition
	at com.coxautodev.graphql.tools.SchemaClassScanner.<init>(SchemaClassScanner.kt:656)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:149)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:155)
```

Looks like `TypeExtensionDefinition` has been renamed to `ObjectTypeExtensionDefinition`.

**Comment by rwilliams-r7** [comment]
I have a branch for the upgrade how to I get access to the repo to add my branch and PR?

**Comment by rwilliams-r7** [comment]
https://github.com/graphql-java/graphql-java-tools/pull/130

**Comment by rwilliams-r7** [comment]
This is also needed to upgrade from Java8, so we can use the correct version of graphql-java.

**Comment by slisaasquatch** [comment]
Looks like this has been fixed in the latest release. 👍
