### ISSUE TITLE
Provide an example for Union types

### ISSUE THREAD

**Issue by BenoitAverty** [graphql-java/graphql-java-tools#13]
Hello,

I'm having a bit of trouble implementing a union type with this library. Could you provide an example in the readme ?

Here is the schema I'm trying to implement, but I don't know which classes to provide or if I have to do something in te builder.

```
union CodePointValue = Int|String

type Query {
    codepoint(value: CodepointValue!): Codepoint
}

type Codepoint {
    value: Int!
    name: String!
}
```

And the config : 
```java
SchemaParser.newParser()
                .file("schema.graphqls")
                .dictionary(Codepoint.class)
                .resolvers(resolvers)
                .build()
                .makeExecutableSchema()
        ;
    }
```

Thanks in advance

**Comment by apottere** [comment]
I can provide an example, but you shouldn't have to do anything special for Union types to work.  Just define a method on your resolver that returns the closest common parent between the types (in this case, Object), and it should just work.

**Comment by acidbluebriggs** [comment]
It's unfortunate that Kotlin, nor Java, have Union types. As @apottere mentioned, your resolver will just have to return the common parent. In Kotlin I had to return 'Any'. If you are using Kotlin, you could probably used a sealed class that could help describe the result more clearly though. But, sometimes that just isn't enough as you might have types you wish to return that aren't already sealed, so that becomes difficult.

The only way you can really tell that there is an issue with the return value of an 'Object' or 'Any', is that you'll find out at runtime that your resolver returned the wrong type.

**Comment by BenoitAverty** [comment]
Thanks for your answers. Unformtunately I still didn't make it work. 

The first thing is that you both mentioned return types but in my case, the Union is used in a parameter.

So I did this : 
schema.graphqls: 
```
union CodepointValue =  Int|String

type Query {
    codepoints: [Codepoint!]
    codepoint(value: CodepointValue!): Codepoint
}

type Codepoint {
    value: Int!
    name: String!
    properties: Properties!
}

type Properties {
    name: String!
    block: String!
}
```

and in my Resolver I take `Object` as an argument.
```java
public Codepoint codepoint(Object value) {
        if(Integer.class.isAssignableFrom(value.getClass())) {
            return codepointQueryHandler.findCodepoint((Integer) value).orElseThrow(CodepointNotFound::new);
        }
        else if(String.class.isAssignableFrom(value.getClass())) {
            return codepointQueryHandler.findCodepoint((String) value).orElseThrow(CodepointNotFound::new);
        }
        else {
            log.error("Codepoint query resolver was called wit an incorrect parameter. Value parameter must be an integer or a string.");
            throw new IllegalArgumentException("Codepoint value must be an integer or a string.");
        }
    }
```

Unfortunately I get this exception : 
```
Caused by: com.coxautodev.graphql.tools.SchemaError: Expected object type 'Int' for union type 'CodepointValue', but found none!
	at com.coxautodev.graphql.tools.SchemaParser.createUnionObject(SchemaParser.kt:319) ~[graphql-java-tools-2.1.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaParser.parseSchemaObjects(SchemaParser.kt:204) ~[graphql-java-tools-2.1.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaParser.makeExecutableSchema(SchemaParser.kt:229) ~[graphql-java-tools-2.1.3.jar:na]
	at org.unicodetool.graphql.GraphQLConfiguration.graphQLSchema(GraphQLConfiguration.java:35) ~[main/:na]
	at org.unicodetool.graphql.GraphQLConfiguration$$EnhancerBySpringCGLIB$$8db0b01e.CGLIB$graphQLSchema$2(<generated>) ~[main/:na]
	at org.unicodetool.graphql.GraphQLConfiguration$$EnhancerBySpringCGLIB$$8db0b01e$$FastClassBySpringCGLIB$$6d1ddf40.invoke(<generated>) ~[main/:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.0.RC1.jar:5.0.0.RC1]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-5.0.0.RC1.jar:5.0.0.RC1]
	at org.unicodetool.graphql.GraphQLConfiguration$$EnhancerBySpringCGLIB$$8db0b01e.graphQLSchema(<generated>) ~[main/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_121]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_121]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-5.0.0.RC1.jar:5.0.0.RC1]
	... 22 common frames omitted
```

It almost looks like a type Int is expected in the schema, but it's a basic type, I didn't have to define it for other places I use it in.

**Comment by apottere** [comment]
Unions and interfaces aren't allowed in arguments per the graphql spec,
sorry :(

**Comment by BenoitAverty** [comment]
Aaah that explains it then :)
Thanks, that's a very clear and definitive answer ^^

**Comment by BenoitAverty** [comment]
So I looked a little bit closer, and it turns out my use case was better addressed by a Scalar type anyway.  I implemented a custom scalar type that is able to parse a string or int value in the query.

Thanks all for your answers.

**Comment by apottere** [comment]
I'm pretty sure the specific error you're seeing is because you can't use scalar types for unions, actually.  I should write a test to make sure it actually validates that unions and interfaces can't be argument types, because I'm not sure it enforces that yet.
