### ISSUE TITLE
Issue with graphql-java-tools v5.0.0

### ISSUE THREAD

**Issue by ravi7karuturi** [graphql-java/graphql-java-tools#138]
I have upgraded to v5.0.0 to use the batching functionalities for calling an API, but getting issues with the newer version, do we need to add any additional dependencies?

 Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.servlet.GraphQLServlet]: Factory method 'graphQLServlet' threw exception; nested exception is java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.7.RELEASE.jar:4.3.7.RELEASE]
	... 18 common frames omitted
Caused by: java.lang.NoClassDefFoundError: graphql/execution/instrumentation/NoOpInstrumentation
	at graphql.servlet.SimpleGraphQLServlet.<init>(SimpleGraphQLServlet.java:44) ~[graphql-java-servlet-4.6.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLWebAutoConfiguration.graphQLServlet(GraphQLWebAutoConfiguration.java:155) ~[graphql-spring-boot-autoconfigure-4.0.0.jar:na]

**Comment by apottere** [comment]
This is an issue with the servlet, and has been resolved in the latest version 👍
