### ISSUE TITLE
Does graphql-java tools support object-types with methods and field resolvers?

### ISSUE THREAD

**Issue by garethpenfold** [graphql-java/graphql-java-tools#175]
I have a Class which has three different GraphQL "types"
- Basic Type
- Method Type
- Resolvable Field Type

This can been seen in the following schema (specifically in book):
```
type Book {
    id: Int!
    name: String! #Basic type
    author: Author! #Resolvable Field Type
    inStock(storeId: Int): Boolean #Method Type
}

type Author {
    id: Int!
    name: String!
}

type Query {
    book: Book
}

schema {
    query: Query
}
```
I have been able to set up a successful example application for all combinations with the exception of pairing a 'method type' with a resolvable field type, using a GraphQLResolver. In this scenario the following exception is thrown:

```
Caused by: kotlin.KotlinNullPointerException: null
	at com.coxautodev.graphql.tools.MethodFieldResolver.scanForMatches(MethodFieldResolver.kt:108) ~[graphql-java-tools-5.2.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanResolverInfoForPotentialMatches(SchemaClassScanner.kt:230) ~[graphql-java-tools-5.2.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueueItemForPotentialMatches(SchemaClassScanner.kt:222) ~[graphql-java-tools-5.2.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanQueue(SchemaClassScanner.kt:106) ~[graphql-java-tools-5.2.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:84) ~[graphql-java-tools-5.2.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:150) ~[graphql-java-tools-5.2.3.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:156) ~[graphql-java-tools-5.2.3.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:57) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$801a91d9.CGLIB$schemaParser$0(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$801a91d9$$FastClassBySpringCGLIB$$553a748d.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:361) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$801a91d9.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-5.0.2.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_102]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_102]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_102]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_102]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 94 common frames omitted
```

Example code can be found https://github.com/garethpenfold/graphql

I am not sure if I have set this up incorrectly, this is something that is not yet supported or if this is a bug?

**Comment by oliemansm** [comment]
Have you tried adding the method to your class `BookResolver` instead?

**Comment by garethpenfold** [comment]
That worked. Thank you for you help! 

It is interesting that prior to adding the `BookResolver` the inStock method resolves correctly to the data class `Book`. I would have thought it would fall back to the `Book` class after finding no match in the `BookResolver`, or vice versa.
