### ISSUE TITLE
Nested input types are not working

### ISSUE THREAD

**Issue by rtti** [graphql-java/graphql-java-tools#26]
I have such schema root.graphqls:

```
input AuthorInput {
    id: Int
    name: String!
}

input BookInput {
    id: Int!
    name: String
    authorInput: AuthorInput
}

type BookMutation {
    createBook(bookInput: BookInput!): Book
}

//other types
```
and appropriate java model classes. When I run 

```
SchemaParser schemaParser = SchemaParser.newParser()
                .file("my/model/root.graphqls")
                .resolvers(new QueryResolver(bookRepository), new MutationResolver(bookRepository))
                .build();

GraphQLSchema graphQLSchema = schemaParser.makeExecutableSchema();
```
I get `[main] WARN  c.c.g.t.SchemaClassScanner - Schema type was defined but can never be accessed, and can be safely deleted: AuthorInput`

and

```
Exception in thread "main" graphql.GraphQLException: type AuthorInput not found in schema
	at graphql.schema.SchemaUtil.resolveTypeReference(SchemaUtil.java:217)
	at graphql.schema.GraphQLInputObjectField.replaceTypeReferences(GraphQLInputObjectField.java:44)
	at graphql.schema.SchemaUtil.resolveTypeReferencesForInputFieldsContainer(SchemaUtil.java:209)
	at graphql.schema.SchemaUtil.replaceTypeReferences(SchemaUtil.java:187)
	at graphql.schema.GraphQLSchema$Builder.build(GraphQLSchema.java:131)
	at com.coxautodev.graphql.tools.SchemaObjects.toSchema(SchemaObjects.kt:18)
	at com.coxautodev.graphql.tools.SchemaParser.makeExecutableSchema(SchemaParser.kt:83)
	at my.graphql.Main.main(Main.java:28)
```
According to spec:

> Input types can't have fields that are other objects, only basic scalar types, list types, and other input types.

Do I use this in some wrong way?

**Comment by rtti** [comment]
The only way I can workaround this is a quite odd construction:

```
SchemaObjects schemaObjects = schemaParser.parseSchemaObjects();
        GraphQLInputObjectType authorInput = GraphQLInputObjectType.newInputObject()
                .name("AuthorInput")
                .field(newInputObjectField()
                        .name("id")
                        .type(GraphQLString))
                .field(newInputObjectField()
                        .name("name")
                        .type(new GraphQLNonNull(GraphQLString)))
                .build();
        schemaObjects.getDictionary().add(authorInput);

        GraphQLSchema graphQLSchema = GraphQLSchema.newSchema()
                .query(schemaObjects.getQuery())
                .mutation(schemaObjects.getMutation())
                .build(schemaObjects.getDictionary());
```
But I intend to use graphql-java-tools to avoid such declarations of types

**Comment by apottere** [comment]
Yeah, that's definitely a bug.  I'll take a look.
