### ISSUE TITLE
Help w/ simple POJO

### ISSUE THREAD

**Issue by efenderbosch** [graphql-java/graphql-java-tools#43]
I've got a simple Address POJO, just a few String attributes and an id.

`SchemaParser.newParser().dictionary(Address.class).build().makeExecutableSchema()`

I get this exception:

```
org.antlr.v4.runtime.misc.ParseCancellationException
at org.antlr.v4.runtime.BailErrorStrategy.recover(BailErrorStrategy.java:75)
at graphql.parser.antlr.GraphqlParser.definition(GraphqlParser.java:260)
at graphql.parser.antlr.GraphqlParser.document(GraphqlParser.java:166)
at graphql.parser.Parser.parseDocument(Parser.java:29)
at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:101)
at com.test.graphql.GraphQLTest.test_SchemaParser(GraphQLTest.java:49)
...
Caused by: org.antlr.v4.runtime.NoViableAltException
at graphql.parser.antlr.GraphqlParser.definition(GraphqlParser.java:254)
```

What am I missing?

**Comment by apottere** [comment]
That means your schema syntax isn't correct - the error messages have been improved but haven't been released yet.  If you debug `SchemaParserBuilder.kt:101` you can see the line number that's causing the parser to fail.

**Comment by efenderbosch** [comment]
Looks like GraphqlParser.java line 220 switch statement is falling through to the default case at line 254 which throws NoViableAltException.

**Comment by apottere** [comment]
The exception thrown should have line information that will tell you the invalid token.

**Comment by efenderbosch** [comment]
Can't SchemaBuilder be used to create a skeleton schema from existing POJOs? I just want to add our POJOs, generate a schema and manipulate it from there.

**Comment by apottere** [comment]
Oh, no.  graphql-java-tools is schema-first, so it can't be used without a schema.

**Comment by efenderbosch** [comment]
Ok, thanks. I'll probably write something to do it via reflection then.

**Comment by apottere** [comment]
You might be interested in https://github.com/graphql-java/graphql-java-annotations if you haven't seen it already.
