### ISSUE TITLE
Interfaces - having multiple interfaces in schema generates errors on startup

### ISSUE THREAD

**Issue by Silvatre** [graphql-java/graphql-java-tools#45]
**Issue**
If schema has multiple interfaces, then the app fails to start.

**Reproduction**
Given the following example schema and its corresponding java classes:

```javascript
type Query {
    query1(resource: NamedResourceImpl): [Long!]
    query2(resource: VersionedResourceImpl): [Long!]
}


interface NamedResource {
    name: String!
}

interface VersionedResource {
    version: Int!
}

type NamedResourceImpl implements NamedResource {
    name: String!
}

type VersionedResourceImpl implements VersionedResource {
    version: Int!
}
```

When the application is starting,

The following exception is being thrown:
```
Caused by: com.coxautodev.graphql.tools.SchemaClassScannerError: Error creating bimap of type => class
	at com.coxautodev.graphql.tools.SchemaClassScanner.validateAndCreateParser(SchemaClassScanner.kt:141) ~[graphql-java-tools-3.2.1.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:124) ~[graphql-java-tools-3.2.1.jar:na]

Caused by: java.lang.IllegalArgumentException: value already present: null
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:287) ~[guava-21.0.jar:na]
	at com.google.common.collect.HashBiMap.put(HashBiMap.java:262) ~[guava-21.0.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.validateAndCreateParser(SchemaClassScanner.kt:138) ~[graphql-java-tools-3.2.1.jar:na]
	... 81 common frames omitted
```

**Comment by apottere** [comment]
I think I know what's causing this, and a workaround till I get it fixed might be to create dummy fields that return the interface type.

Since there are no actual fields that return the interfaces, it doesn't know what class to map them to.  It *should* be filtering them out, and I'll fix that as soon as I can.
