### ISSUE TITLE
Exception if Schema have more than one types having multiple implementations.

### ISSUE THREAD

**Issue by gkarthics** [graphql-java/graphql-java-tools#51]
In a schema, if there is only one type having two implementations its working fine. 

But if there is another type object which also has two implementations like shown below, 

```
interface FirstInterface {
  firstInterfaceValue : String
}

interface SecondInterface {
	secondInterfaceValue : String
}

type FirstImpl implements FirstInterface {
    firstInterfaceValue : String
    firstImplId: ID!
    firstImplValue: String
    dataType : DataType
}

type SecondImpl implements SecondInterface, FirstInterface {
    secondImplId: ID!
    secondImplValue: String
    secondInterfaceValue : String
    firstInterfaceValue : String
}

type ThirdImpl implements SecondInterface, FirstInterface {
    secondImplId: ID!
    secondImplValue: String
    secondInterfaceValue : String
    firstInterfaceValue : String
}
```

I am getting the following exception.

`
com.coxautodev.graphql.tools.SchemaClassScannerError: Object type 'ThirdImpl' implements a known interface, but no class was found for that type name.  Please pass a class for type 'ThirdImpl' in the parser's dictionary.
	at com.coxautodev.graphql.tools.SchemaClassScanner.handleInterfaceOrUnionSubTypes(SchemaClassScanner.kt:183)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:89)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:125)
	at com.graphql.GraphQLEndpoint.buildSchema(GraphQLEndpoint.java:26)
	at com.graphql.GraphQLEndpoint.<init>(GraphQLEndpoint.java:16)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at java.lang.Class.newInstance(Class.java:442)
	at org.eclipse.jetty.server.handler.ContextHandler$Context.createInstance(ContextHandler.java:2470)
	at org.eclipse.jetty.servlet.ServletContextHandler$Context.createServlet(ServletContextHandler.java:1327)
	at org.eclipse.jetty.servlet.ServletHolder.newInstance(ServletHolder.java:1220)
	at org.eclipse.jetty.servlet.ServletHolder.initServlet(ServletHolder.java:612)
	at org.eclipse.jetty.servlet.ServletHolder.getServlet(ServletHolder.java:496)
	at org.eclipse.jetty.servlet.ServletHolder.ensureInstance(ServletHolder.java:788)
	at org.eclipse.jetty.servlet.ServletHolder.prepare(ServletHolder.java:773)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:578)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:548)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:226)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1174)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1106)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:213)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:119)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:134)
	at org.eclipse.jetty.server.Server.handle(Server.java:524)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:319)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:253)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:273)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
	at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:93)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.executeProduceConsume(ExecuteProduceConsume.java:303)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceConsume(ExecuteProduceConsume.java:148)
	at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by gkarthics** [comment]
The sample code is in this repo, can you please take a look at that 
https://github.com/gkarthics/graphql-java-tools-multiple-interface-example

**Comment by jffiorillo** [comment]
@apottere said:

> Yeah, `ThirdImpl` isn't referenced from any resolver methods so you'll have to tell graphql-java-tools what type it is. There's no other way for it to figure out the java type.


how can I say the type that it is without adding a query to the type? Image I have 

```
interface W{
  type: C
}

type X implement W{
  type: C
  name: String
}
```

and I just want to be able to query 

```
type Query{
  getAllW: [W]!
}
```

I don't want to have to add `getX` to `Query`... Is this possible?

Thank you
