### ISSUE TITLE
Use input types in unions

### ISSUE THREAD

**Issue by miguelaferreira** [graphql-java/graphql-java-tools#59]
Following a [discussion](https://github.com/graphql/graphql-js/issues/207#issuecomment-243638111) about how to use unions for input types I wrote the following schema.
```gql
union LocationInput = GeoLocationInput | AddressInput

input GeoLocationInput {
  lat: Float!
  lng: Float!
}

input AddressInput {
  street: String!
  number: String!
  postCode: String!
  place: String!
}
```

When processing my schema I get the following error:
```
com.coxautodev.graphql.tools.SchemaClassScannerError: TODO

	at com.coxautodev.graphql.tools.SchemaClassScanner.getAllObjectTypeMembersOfDiscoveredUnions(SchemaClassScanner.kt:170)
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:121)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:118)
	at com.careibu.landing.graphql.SchemaTest.testSchema(SchemaTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:316)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:114)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.lambda$invokeTestMethod$6(MethodTestDescriptor.java:171)
	at org.junit.jupiter.engine.execution.ThrowableCollector.execute(ThrowableCollector.java:40)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.invokeTestMethod(MethodTestDescriptor.java:168)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:115)
	at org.junit.jupiter.engine.descriptor.MethodTestDescriptor.execute(MethodTestDescriptor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:81)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.lambda$execute$1(HierarchicalTestExecutor.java:91)
	at org.junit.platform.engine.support.hierarchical.SingleTestExecutor.executeSafely(SingleTestExecutor.java:66)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:76)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:51)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:43)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:137)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:87)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:62)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

Looking at the code it seems to me like the method `com.coxautodev.graphql.tools.SchemaClassScanner.getAllObjectTypeMembersOfDiscoveredUnions(SchemaClassScanner.kt:170)` expects all union subtypes to be GraphQL `type` and not `input`.

I've debugged to make sure the definition it's trying to lookup is `GeoLocationInput`.

Am I doing something wrong in my schema definition or is this a limitation of graphql-java-tools?

**Comment by apottere** [comment]
Woops, that error message could definitely be improved.

AFAICT, union input types aren't actually supported in graphql-js, let alone graphql-java.  Does the schema above work when building it without graphql-java-tools?

**Comment by miguelaferreira** [comment]
I don't know, I'm new to this. But I'll try building it with graphql-js and let you know.

**Comment by andimarek** [comment]
@miguelaferreira @miguelaferreira input types are only allowed for field arguments. Union/Interfaces are only for output, so they are not allowed to be used as input.

**Comment by miguelaferreira** [comment]
Thanks very much for the quick reply and the info. I'll go ahead and close the issue.
