### ISSUE TITLE
Failed to start SpringBoot Application after addition of graphql

### ISSUE THREAD

**Issue by swapnilbagadia** [graphql-java/graphql-java-tools#67]
Dependencies added : 

<dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-spring-boot-starter</artifactId>
            <version>3.6.0</version>
</dependency>
<dependency>
            <groupId>com.graphql-java</groupId>
            <artifactId>graphql-java-tools</artifactId>
            <version>3.2.0</version>
</dependency>

Schema - 
schema {
    query: Query
}

type Query {
    shipments(): [ShipmentRouteEvent]!
}

type ShipmentRouteEvent {
    routeEventId: Long!
    routeLegId: Long!
    shipmentId: String!
}

Query - 

@Component
public class Query implements GraphQLQueryResolver {

    ShipmentRouteEventRepository shipmentRouteEventRepository;

    public Query (ShipmentRouteEventRepository shipmentRouteEventRepository){
        this.shipmentRouteEventRepository = shipmentRouteEventRepository;
    }

    public List<ShipmentRouteEvent> getShipments() {
        return shipmentRouteEventRepository.findAll();
    }
}

When I start the application, I get - 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schemaParser' defined in class path resource [com/oembedler/moon/graphql/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is org.antlr.v4.runtime.misc.ParseCancellationException
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107)
	at com.fkart.api.DemoApplication.main(DemoApplication.java:34)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.coxautodev.graphql.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is org.antlr.v4.runtime.misc.ParseCancellationException
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
	... 23 common frames omitted
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException: null
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
	at graphql.parser.antlr.GraphqlParser.name(GraphqlParser.java:1361)
	at graphql.parser.antlr.GraphqlParser.inputValueDefinition(GraphqlParser.java:3099)
	at graphql.parser.antlr.GraphqlParser.argumentsDefinition(GraphqlParser.java:3037)
	at graphql.parser.antlr.GraphqlParser.fieldDefinition(GraphqlParser.java:2965)
	at graphql.parser.antlr.GraphqlParser.objectTypeDefinition(GraphqlParser.java:2834)
	at graphql.parser.antlr.GraphqlParser.typeDefinition(GraphqlParser.java:2654)
	at graphql.parser.antlr.GraphqlParser.typeSystemDefinition(GraphqlParser.java:2437)
	at graphql.parser.antlr.GraphqlParser.definition(GraphqlParser.java:250)
	at graphql.parser.antlr.GraphqlParser.document(GraphqlParser.java:166)
	at graphql.parser.Parser.parseDocument(Parser.java:29)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:101)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:63)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2818b27b.CGLIB$schemaParser$0(<generated>)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2818b27b$$FastClassBySpringCGLIB$$8af61f60.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$2818b27b.schemaParser(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 24 common frames omitted
Caused by: org.antlr.v4.runtime.InputMismatchException: null
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
	... 46 common frames omitted

**Comment by apottere** [comment]
It sounds like you have a syntax error in your schema.  Are you using the latest versions?  It should have a more descriptive error.  I'm guessing it's on this line: `shipments():`

**Comment by apottere** [comment]
Closing because of no response.
