### ISSUE TITLE
empty input type schema support

### ISSUE THREAD

**Issue by rolandkozma** [graphql-java/graphql-java-tools#70]
input MyInputType {
}

I think it would be useful to support this kind of input in order to be able to evolve the object structure later, to have a versionless api.

**Comment by apottere** [comment]
It looks like this is disallowed by `graphql-java`:
```
com.coxautodev.graphql.tools.InvalidSchemaError: Invalid schema provided (org.antlr.v4.runtime.InputMismatchException) at: [@15,194:194='}',<7>,8:20]

	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:117)
	at com.coxautodev.graphql.tools.SchemaClassScannerSpec.scanner handles empty input type(SchemaClassScannerSpec.groovy:385)
Caused by: org.antlr.v4.runtime.misc.ParseCancellationException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:90)
	at graphql.parser.antlr.GraphqlParser.name(GraphqlParser.java:1362)
	at graphql.parser.antlr.GraphqlParser.inputValueDefinition(GraphqlParser.java:3116)
	at graphql.parser.antlr.GraphqlParser.inputObjectTypeDefinition(GraphqlParser.java:3589)
	at graphql.parser.antlr.GraphqlParser.typeDefinition(GraphqlParser.java:2699)
	at graphql.parser.antlr.GraphqlParser.typeSystemDefinition(GraphqlParser.java:2454)
	at graphql.parser.antlr.GraphqlParser.definition(GraphqlParser.java:251)
	at graphql.parser.antlr.GraphqlParser.document(GraphqlParser.java:167)
	at graphql.parser.Parser.parseDocument(Parser.java:29)
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:113)
	... 1 more
Caused by: org.antlr.v4.runtime.InputMismatchException
	at org.antlr.v4.runtime.BailErrorStrategy.recoverInline(BailErrorStrategy.java:85)
	... 10 more
```

And furthermore, it looks like it isn't supported by `graphql-js`, either: https://github.com/graphql/graphql-js/issues/937

You could open up an issue for this on `graphql-java`, but since they like to stay as close to the reference implementation as possible they probably won't make any changes till that `graphql-js` issue is resolved.

**Comment by sammyhk** [comment]
Link to graphql-java/graphql-java#903
