### ISSUE TITLE
Schema introspection error on argument of type 'list of enum' specifying a default value

### ISSUE THREAD

**Issue by lburja** [graphql-java/graphql-java-tools#92]
Given the following schema, which contains an input argument of type 'list of enums' with a default value:
```
type Query {
    users(
        statuses: [Status] = [ACTIVE]
    ): [String]
}

enum Status {
    ACTIVE, INACTIVE
}
```

the following introspection query generates an error:
```
{
   __type(name: "Query") {
       name
       fields {
         name
         args {
           name
           defaultValue
         }
       }
   }
}
```

Stacktrace:
```
Exception while fetching data (/__type/fields[0]/args[0]/defaultValue) : Invalid input for Enum 'Status'. Unknown value '[Ljava.lang.Object;@ff2197'

graphql.schema.CoercingSerializeException: Invalid input for Enum 'Status'. Unknown value '[Ljava.lang.Object;@ff2197'
	at graphql.schema.GraphQLEnumType.getNameByValue(GraphQLEnumType.java:137) ~[graphql-java-8.0.jar:na]
	at graphql.schema.GraphQLEnumType.access$000(GraphQLEnumType.java:29) ~[graphql-java-8.0.jar:na]
	at graphql.schema.GraphQLEnumType$1.serialize(GraphQLEnumType.java:40) ~[graphql-java-8.0.jar:na]
	at graphql.language.AstValueHelper.serialize(AstValueHelper.java:174) ~[graphql-java-8.0.jar:na]
	at graphql.language.AstValueHelper.astFromValue(AstValueHelper.java:81) ~[graphql-java-8.0.jar:na]
	at graphql.language.AstValueHelper.handleList(AstValueHelper.java:151) ~[graphql-java-8.0.jar:na]
	at graphql.language.AstValueHelper.astFromValue(AstValueHelper.java:66) ~[graphql-java-8.0.jar:na]
	at graphql.introspection.Introspection.print(Introspection.java:117) ~[graphql-java-8.0.jar:na]
```

**Comment by lburja** [comment]
Fixed in 5.1.0
