### ISSUE TITLE
Not able to use multiple Enums

### ISSUE THREAD

**Issue by regcole** [graphql-java/graphql-java-tools#96]
## Steps to reproduce

```

type Query {
    
     objectsByShape(shape: TypeOne): [object]
    objectsByColor(color: TypeTwo): [object]

}
enum TypeOne {
    SQUARE,
    RECTANGLE,
    CIRCLE
 }

enum TypeTwo {
    ORANGE,
    YELLOW,
    BLUE
 }
```

## Error Produced
`TypeOne` and `TypeTwo` will both attempt to have a value of `String`; causing it to fail once attempting to put these into a biMap.

```
Caused by: com.coxautodev.graphql.tools.SchemaClassScannerError: Error creating bimap of type => class
	at com.coxautodev.graphql.tools.SchemaClassScanner.validateAndCreateResult(SchemaClassScanner.kt:138) ~[graphql-java-tools-4.3.0.jar:na]
	at com.coxautodev.graphql.tools.SchemaClassScanner.scanForClasses(SchemaClassScanner.kt:94) ~[graphql-java-tools-4.3.0.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.scan(SchemaParserBuilder.kt:149) ~[graphql-java-tools-4.3.0.jar:na]
	at com.coxautodev.graphql.tools.SchemaParserBuilder.build(SchemaParserBuilder.kt:155) ~[graphql-java-tools-4.3.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration.schemaParser(GraphQLJavaToolsAutoConfiguration.java:71) ~[graphql-spring-boot-autoconfigure-3.10.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$325a4e7b.CGLIB$schemaParser$0(<generated>) ~[graphql-spring-boot-autoconfigure-3.10.0.jar:na]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$325a4e7b$$FastClassBySpringCGLIB$$be72e53f.invoke(<generated>) ~[graphql-spring-boot-autoconfigure-3.10.0.jar:na]
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228) ~[spring-core-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at com.oembedler.moon.graphql.boot.GraphQLJavaToolsAutoConfiguration$$EnhancerBySpringCGLIB$$325a4e7b.schemaParser(<generated>) ~[graphql-spring-boot-autoconfigure-3.10.0.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_144]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.__invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[na:1.8.0_144]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java) ~[na:1.8.0_144]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_144]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 82 common frames omitted
Caused by: java.lang.IllegalArgumentException: value already present: class java.lang.String
```

**Comment by apottere** [comment]
Are you using `String` somewhere you should be using `TypeOne` or `TypeTwo`?  You can try passing those enums to the parser in the dictionary and it should let you know where the problem is.

**Comment by regcole** [comment]
@apottere thanks for the tip. The error was caused by a root (programmer side) problem of there not being a backing Java enum. Closing issue.

**Comment by apottere** [comment]
👍 glad you got it working.
